<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ElkollegeGuidanceBot-8cfb9ee1-5971-4efe-8f4d-26878839971c</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.1"/>
        <PackageReference Include="Dapper" Version="2.1.89" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12"/>
        <PackageReference Include="Telegram.BotAPI" Version="10.3.0"/>
        <PackageReference Include="Telegram.BotAPI.Extensions" Version="0.8.2"/>
    </ItemGroup>
</Project>
